// Generated by Claude Code from spec.md in 90 seconds.
import { test, expect } from "@playwright/test";

test.describe("Pomodoro", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("file://" + process.cwd() + "/demos/01-mvp-pomodoro/index.html");
  });

  test("starts at 25:00 in FOCUS mode", async ({ page }) => {
    await expect(page.locator("#timer")).toHaveText("25:00");
    await expect(page.locator("#mode")).toHaveText("FOCUS");
  });

  test("ticks down after START", async ({ page }) => {
    await page.click("#start");
    await page.waitForTimeout(1100);
    const txt = await page.locator("#timer").textContent();
    expect(txt).toBe("24:59");
  });

  test("PAUSE freezes the timer", async ({ page }) => {
    await page.click("#start");
    await page.waitForTimeout(1100);
    await page.click("#pause");
    const frozen = await page.locator("#timer").textContent();
    await page.waitForTimeout(1500);
    expect(await page.locator("#timer").textContent()).toBe(frozen);
  });

  test("RESET returns to 25:00", async ({ page }) => {
    await page.click("#start");
    await page.waitForTimeout(1500);
    await page.click("#reset");
    await expect(page.locator("#timer")).toHaveText("25:00");
    await expect(page.locator("#mode")).toHaveText("FOCUS");
  });

  test("stats persist across reloads", async ({ page }) => {
    await page.evaluate(() => {
      const log = [{ ts: Date.now() }];
      localStorage.setItem("pomo.log", JSON.stringify(log));
    });
    await page.reload();
    await expect(page.locator("#today")).toHaveText("1");
    await expect(page.locator("#total")).toHaveText("1");
  });
});
